config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create]

  resources :questions

  resources :answers

  resources :votes, only: [:new, :create]

  resources :comments

  resources :tags, only: [:new, :create, :show]

  resources :sessions, only: [:destory, :new, :create]

  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

  root 'questions#index'

  get 'questions/:id/answers' => 'questions#answers', as: :question_answers

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  belongs_to :question
  has_many :votes, as: :voteable
  has_many :comments, as: :commentable

  validates_presence_of :content, :author
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentor, class_name: 'User', foreign_key: :user_id
  belongs_to :commentable, polymorphic: true

  validates_presence_of :content

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: :user_id
  has_many :answers
  has_many :votes, as: :voteable
  has_many :comments, as: :commentable
  has_many :question_tags
  has_many :tags, through: :question_tags

  validates_presence_of :title, :content, :author
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :question_tags
  has_many :questions, through: :question_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :answers
  has_many :questions
  has_many :comments
  has_many :votes
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_confirmation_of :password
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voter, class_name: 'User', foreign_key: :user_id
  belongs_to :voteable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save && user_params[:password] == user_params[:password_confirmation]
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "/sessions/new"
    end
  end

  private

  def user_params
    user_params = params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Clone Overflow", questions_path %></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
  <% if logged_in? %>
    <ul class="right">
      <li><%= link_to "Log Out", logout_path %></li>
    </ul>
  <% else %>
    <ul class="right">
      <li><%= link_to "Sign Up", new_user_path %></li>
      <li><%= link_to "Log In", login_path %></li>
    </ul>
  <% end %>
  </section>
</nav>

    <%= yield %>

  </body>
</html>